# Embeds every file of a directory into a target as C++ byte arrays.
#
#   easy_webview_embed_dir(<target> <name> <dir>)
#
# Generates <name>.h / <name>.cpp in the binary dir and adds them to <target>.
# The header declares:
#
#   extern const std::map<std::string, std::string_view> <name>;
#
# mapping URL paths ("/index.html", "/vendor/x.css", ...) to file contents.
# The .cpp is regenerated at build time whenever a file in <dir> changes
# (adding or removing files re-runs the configure step).

# --- Script mode: cmake -DEMBED_DIR=... -DEMBED_NAME=... -DEMBED_OUTPUT=... -P embed_dir.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    file(GLOB_RECURSE files RELATIVE "${EMBED_DIR}" "${EMBED_DIR}/*")
    list(SORT files)

    string(REPEAT "0x..," 32 line_pattern) # wrap output every 32 bytes
    set(arrays "")
    set(entries "")
    set(index 0)
    foreach(rel IN LISTS files)
        file(SIZE "${EMBED_DIR}/${rel}" size)
        if(size EQUAL 0)
            set(bytes "0") # zero-sized arrays are not allowed
        else()
            file(READ "${EMBED_DIR}/${rel}" hex HEX)
            string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
            string(REGEX REPLACE "(${line_pattern})" "\\1\n" bytes "${bytes}")
        endif()

        set(key "/${rel}")
        string(REPLACE "\\" "\\\\" key "${key}")
        string(REPLACE "\"" "\\\"" key "${key}")

        string(APPEND arrays "// ${rel}\nstatic const unsigned char file_${index}[] = {\n${bytes}\n};\n\n")
        string(APPEND entries "    {\"${key}\", {reinterpret_cast<const char *>(file_${index}), ${size}}},\n")
        math(EXPR index "${index} + 1")
    endforeach()

    file(WRITE "${EMBED_OUTPUT}"
        "// Generated by embed_dir.cmake from ${EMBED_DIR} - do not edit.\n"
        "#include \"${EMBED_NAME}.h\"\n\n"
        "${arrays}"
        "extern const std::map<std::string, std::string_view> ${EMBED_NAME} = {\n"
        "${entries}"
        "};\n")
    return()
endif()

# --- Configure mode -------------------------------------------------------------
set(EASY_WEBVIEW_EMBED_DIR_SCRIPT "${CMAKE_CURRENT_LIST_FILE}")

function(easy_webview_embed_dir target name dir)
    get_filename_component(dir "${dir}" ABSOLUTE)
    file(GLOB_RECURSE files CONFIGURE_DEPENDS "${dir}/*")

    set(out_dir "${CMAKE_CURRENT_BINARY_DIR}/embedded")
    set(out_h "${out_dir}/${name}.h")
    set(out_cpp "${out_dir}/${name}.cpp")

    file(CONFIGURE OUTPUT "${out_h}" CONTENT
"// Generated by embed_dir.cmake - do not edit.
#pragma once
#include <map>
#include <string>
#include <string_view>

extern const std::map<std::string, std::string_view> ${name};
")

    add_custom_command(
        OUTPUT "${out_cpp}"
        COMMAND "${CMAKE_COMMAND}"
            "-DEMBED_DIR=${dir}"
            "-DEMBED_NAME=${name}"
            "-DEMBED_OUTPUT=${out_cpp}"
            -P "${EASY_WEBVIEW_EMBED_DIR_SCRIPT}"
        DEPENDS ${files} "${EASY_WEBVIEW_EMBED_DIR_SCRIPT}"
        COMMENT "Embedding ${dir}"
        VERBATIM)

    target_sources(${target} PRIVATE "${out_h}" "${out_cpp}")
    target_include_directories(${target} PRIVATE "${out_dir}")
endfunction()
